### ISSUE TITLE
Correct display of information button

### ISSUE THREAD

**Issue by debanjana-a11y** [debanjana-a11y/TodoList#1]
Information button is a fake .png file and in mobile the checkered backgroud is obvious. Also the circle looks odd and uneven circle. Make it better looking.

![Issue_1_info_button](https://user-images.githubusercontent.com/89571066/195505628-68a5b111-201e-4223-b0d6-237c77a216d0.png)

**Comment by tenocijam** [comment]
Hi, I would like to work on this

**Comment by debanjana-a11y** [comment]
The fix worked so closing this issue.
