### ISSUE TITLE
Edit button looks off-putting in odd circle shape 

### ISSUE THREAD

**Issue by debanjana-a11y** [debanjana-a11y/TodoList#2]
The circles look odd in "edit button". the "delete" button too have it but less obvious.

Improve the display of both of these buttons.

![Issue_2_edit_delete](https://user-images.githubusercontent.com/89571066/195506280-a897030e-441f-4117-85b4-26625cb04559.png)

**Comment by Vansh-Baghel** [comment]
Lemme try this out

**Comment by Ritika-Pandey01** [comment]
I would like to take this issue.

**Comment by debanjana-a11y** [comment]
> I would like to take this issue.

Hi @Ritika-Pandey01, thanks for the interest but this is solved as of now. Do you have any suggestion to improve these buttons ? I can create one issue for this and assign to you or you can take a look on existing open issues ?
