### ISSUE TITLE
Save current Project and Tasks informations in localStorage

### ISSUE THREAD

**Issue by debanjana-a11y** [debanjana-a11y/TodoList#5]
Add saving informations locally using localStorage, so that user can see latest information after refreshing page in browser.

**Comment by Ayush-Kanduri** [comment]
Hi, @debanjana-a11y please assign the issue to me, would love to work on it.

**Comment by debanjana-a11y** [comment]
Changes are being saved after browser refreshing and reopening. 
![image](https://user-images.githubusercontent.com/89571066/195974052-f67d52f0-523f-4ad4-856e-bdf43f07a953.png)

Closing the issue, Thanks @Ayush-Kanduri for your contribution :).

**Comment by Ayush-Kanduri** [comment]
Is it working as expected @debanjana-a11y ?
